export const allPricingPlans = {
  "mobile-development": [
    {
      name: "Starter",
      price: "$599",
      period: "/project",
      description: "Perfect for small mobile app startups",
      features: [
        "Basic UI/UX design",
        "Android & iOS support",
        "Up to 5 screens",
        "Basic animations",
        "Push notifications",
        "1 month support",
      ],
      notIncluded: [
        "Custom backend",
        "Advanced analytics",
        "App Store publishing",
      ],
      isPopular: false,
      buttonText: "Get Started",
      color: "border-gray-200",
    },
    {
      name: "Business",
      price: "$999",
      period: "/project",
      description: "Popular choice for growing apps",
      features: [
        "Custom app functionality",
        "Database integration",
        "6-10 screens",
        "Push notifications & analytics",
        "Payment gateway integration",
        "6 months support",
      ],
      notIncluded: ["Unlimited revisions", "Dedicated account manager"],
      isPopular: true,
      buttonText: "Get Started",
      color: "border-orange",
    },
    {
      name: "Enterprise",
      price: "$1599",
      period: "/project",
      description: "Full-scale mobile solution",
      features: [
        "Unlimited screens",
        "Custom backend & API",
        "Push notifications & analytics",
        "Advanced security",
        "Dedicated support",
        "12 months support",
      ],
      notIncluded: [],
      isPopular: false,
      buttonText: "Contact Sales",
      color: "border-gray-200",
    },
  ],
  "graphic-design": [
    {
      name: "Starter",
      price: "$299",
      period: "/project",
      description: "Basic design packages for startups",
      features: [
        "Logo design",
        "Business card & stationery",
        "Social media graphics",
        "3 initial concepts",
        "1 month support",
      ],
      notIncluded: ["Brand strategy", "Animation", "Website design"],
      isPopular: false,
      buttonText: "Get Started",
      color: "border-gray-200",
    },
    {
      name: "Business",
      price: "$599",
      period: "/project",
      description: "Complete branding and design solutions",
      features: [
        "Logo & brand identity",
        "Marketing materials",
        "Social media branding",
        "Custom illustrations",
        "6 months support",
      ],
      notIncluded: ["Animated videos", "Full website design"],
      isPopular: true,
      buttonText: "Get Started",
      color: "border-orange",
    },
    {
      name: "Enterprise",
      price: "$999",
      period: "/project",
      description: "Comprehensive design and branding",
      features: [
        "Full brand strategy",
        "Logo & visual identity",
        "Marketing & social graphics",
        "Custom illustrations & infographics",
        "Dedicated designer & 12 months support",
      ],
      notIncluded: [],
      isPopular: false,
      buttonText: "Contact Sales",
      color: "border-gray-200",
    },
  ],
  "website-development": [
    {
      name: "Starter",
      price: "$499",
      period: "/project",
      description: "Perfect for simple business websites",
      features: [
        "Up to 5 pages",
        "Responsive design",
        "Basic SEO",
        "Contact form",
        "1 month support",
      ],
      notIncluded: ["Custom backend", "E-commerce", "Advanced SEO"],
      isPopular: false,
      buttonText: "Get Started",
      color: "border-gray-200",
    },
    {
      name: "Business",
      price: "$999",
      period: "/project",
      description: "Full-featured business website",
      features: [
        "Up to 15 pages",
        "Custom design & CMS",
        "SEO optimized",
        "Blog & content integration",
        "6 months support",
      ],
      notIncluded: ["E-commerce", "Dedicated account manager"],
      isPopular: true,
      buttonText: "Get Started",
      color: "border-orange",
    },
    {
      name: "Enterprise",
      price: "$1499",
      period: "/project",
      description: "Enterprise-grade website with custom features",
      features: [
        "Unlimited pages",
        "Custom CMS or backend",
        "Advanced SEO & analytics",
        "Dedicated support & training",
        "12 months support",
      ],
      notIncluded: [],
      isPopular: false,
      buttonText: "Contact Sales",
      color: "border-gray-200",
    },
  ],
  ecommerce: [
    {
      name: "Starter",
      price: "$699",
      period: "/project",
      description: "Basic online store setup",
      features: [
        "Up to 50 products",
        "Payment gateway integration",
        "Basic theme customization",
        "Responsive design",
        "1 month support",
      ],
      notIncluded: [
        "Custom features",
        "Advanced analytics",
        "Marketing automation",
      ],
      isPopular: false,
      buttonText: "Get Started",
      color: "border-gray-200",
    },
    {
      name: "Business",
      price: "$1299",
      period: "/project",
      description: "Advanced e-commerce solution",
      features: [
        "Up to 500 products",
        "Custom design",
        "Inventory & order management",
        "Payment & shipping integrations",
        "6 months support",
      ],
      notIncluded: ["Dedicated account manager"],
      isPopular: true,
      buttonText: "Get Started",
      color: "border-orange",
    },
    {
      name: "Enterprise",
      price: "$2499",
      period: "/project",
      description: "Full-scale enterprise e-commerce",
      features: [
        "Unlimited products",
        "Custom backend & API",
        "Advanced analytics",
        "Marketing & automation tools",
        "Dedicated support team",
        "12 months support",
      ],
      notIncluded: [],
      isPopular: false,
      buttonText: "Contact Sales",
      color: "border-gray-200",
    },
  ],
};